/* ALL ACTIONS TO USE */

/* LOADER */
const SHOW_LOADER = "SHOW_LOADER";
const HIDE_LOADER = "HIDE_LOADER";

/* MODAL */
const SHOW_MODAL = "SHOW_MODAL";
const HIDE_MODAL = "HIDE_MODAL";
const ACCEPT_MODAL = "ACCEPT_MODAL";

/* MODAL */
const TASK_ADD = "TASK_ADD";
const TASK_DELETE = "TASK_DELETE";
const TASK_UPDATE = "TASK_UPDATE";
const TASK_TO_CURRENT = "TASK_TO_CURRENT";

export {
	SHOW_LOADER,
	HIDE_LOADER,
	SHOW_MODAL,
	HIDE_MODAL,
	ACCEPT_MODAL,
	TASK_ADD,
	TASK_DELETE,
	TASK_UPDATE,
	TASK_TO_CURRENT,
};
